### ISSUE TITLE
Auto Update for FPS Mgr not working?

### ISSUE THREAD

**Issue by 1StarDuster** [SaltyMonkey/fps-manager#10]
18:50:17.276] [update] WARNING: Auto-update disabled for module fps-manager!
Not sure why but when I open tool box it says it will not auto update anymore.
Can you help me fix this or show me how to fix?
ty so much

**Comment by SaltyMonkey** [comment]
reinstall it - you edited smth wrong

**Comment by 1StarDuster** [comment]
Ok thanks Salty,
I will try to reinstall after the transfer.
I really appreciate your reply.
FPS manager really worked well.
I am not sure what happened.
But I am new at this so I gues I just remove it from the toolbox and then
get a fresh start from github?
I did not see it as a selection in the modify list.
Thanks again.
Stay safe out there
-Star.Priestess lvl 70
☀😊☀
[image: image.png]

**Comment by SaltyMonkey** [comment]
just remove fps manager in toolbox ui, after dat go into get more mods tab and install it again

**Comment by 1StarDuster** [comment]
kk thanks Salty!
U r so sweet!
It started working again all by itself. I don't know what it was but thank
you!
Stay safe,
Star.Priestess
🎃
