### ISSUE TITLE
Change mode on entering specific towns/areas

### ISSUE THREAD

**Issue by coyotemax** [SaltyMonkey/fps-manager#5]
Hi. Is it possible to add new directive? Something like:

"triggerTown": {
     "all": "0",
     "Highwatch": "potatopc"
}

It's problematic to change every time on entering Highwatch. And if not changed, game crashes as always after some time.

If it's not possible then no problem, just close the issue.

Thanks :)

**Comment by coyotemax** [comment]
Checked some code on your part and on Tera-Toolbox, some OP Codes, and basically it's too much hassle if not impossible. Maybe through coordinates but whatever. Closed

**Comment by SaltyMonkey** [comment]
sad but truth
